export const AUDIT_MODULES = {
  AUTH: 'AUTH',
  SETTINGS: 'SETTINGS',
  INVENTORY: 'INVENTORY',
  INVOICE: 'INVOICE',
  PO: 'PO',
  PRODUCT: 'PRODUCT',
  USER: 'USER',
  RBAC: 'RBAC',
  REPORT: 'REPORT',
  SECURITY: 'SECURITY',
} as const;

export const AUDIT_ACTIONS = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  LOGIN_FAILED: 'LOGIN_FAILED',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED: 'PASSWORD_RESET_COMPLETED',
  TOKEN_REFRESHED: 'TOKEN_REFRESHED',
  UPDATE_SETTING: 'UPDATE_SETTING',
  RESET_SETTING: 'RESET_SETTING',
  TOGGLE_FEATURE_FLAG: 'TOGGLE_FEATURE_FLAG',
  CREATE_INVOICE: 'CREATE_INVOICE',
  RECEIVE_PO: 'RECEIVE_PO',
  STOCK_ADJUSTMENT: 'STOCK_ADJUSTMENT',
  VIEW_REPORT: 'VIEW_REPORT',
  EXPORT_REPORT: 'EXPORT_REPORT',
  EXPORT_AUDIT: 'EXPORT_AUDIT',
} as const;

export const SECURITY_AUDIT_ACTIONS = new Set<string>([
  AUDIT_ACTIONS.LOGIN,
  AUDIT_ACTIONS.LOGOUT,
  AUDIT_ACTIONS.LOGIN_FAILED,
  AUDIT_ACTIONS.PERMISSION_DENIED,
  AUDIT_ACTIONS.PASSWORD_CHANGED,
  AUDIT_ACTIONS.PASSWORD_RESET_REQUESTED,
  AUDIT_ACTIONS.PASSWORD_RESET_COMPLETED,
]);
