export const AUDIT_CATEGORIES = {
  AUTH: 'AUTH',
  INVENTORY: 'INVENTORY',
  SALES: 'SALES',
  PURCHASE: 'PURCHASE',
  SECURITY: 'SECURITY',
  SYSTEM: 'SYSTEM',
  REPORT: 'REPORT',
} as const;

export const AUDIT_MODULES = {
  AUTH: 'AUTH',
  SETTINGS: 'SETTINGS',
  INVENTORY: 'INVENTORY',
  INVOICE: 'INVOICE',
  PO: 'PO',
  PRODUCT: 'PRODUCT',
  USER: 'USER',
  RBAC: 'RBAC',
  REPORT: 'REPORT',
  SECURITY: 'SECURITY',
} as const;

export const AUDIT_ACTIONS = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  LOGIN_FAILED: 'LOGIN_FAILED',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  UNAUTHORIZED_ACCESS: 'UNAUTHORIZED_ACCESS',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED: 'PASSWORD_RESET_COMPLETED',
  TOKEN_REFRESHED: 'TOKEN_REFRESHED',
  UPDATE_SETTING: 'UPDATE_SETTING',
  RESET_SETTING: 'RESET_SETTING',
  TOGGLE_FEATURE_FLAG: 'TOGGLE_FEATURE_FLAG',
  CREATE_INVOICE: 'CREATE_INVOICE',
  CANCEL_INVOICE: 'CANCEL_INVOICE',
  REFUND_INVOICE: 'REFUND_INVOICE',
  CREATE_PO: 'CREATE_PO',
  APPROVE_PO: 'APPROVE_PO',
  RECEIVE_PO: 'RECEIVE_PO',
  STOCK_ADJUSTMENT: 'STOCK_ADJUSTMENT',
  INVENTORY_REBUILD: 'INVENTORY_REBUILD',
  VIEW_REPORT: 'VIEW_REPORT',
  EXPORT_REPORT: 'EXPORT_REPORT',
  EXPORT_AUDIT: 'EXPORT_AUDIT',
  SYSTEM_ERROR: 'SYSTEM_ERROR',
} as const;

export const AUDIT_SOURCES = {
  API: 'API',
  SYSTEM: 'SYSTEM',
  CRON: 'CRON',
  WEBSOCKET: 'WEBSOCKET',
} as const;

const MODULE_CATEGORY_MAP: Record<string, string> = {
  [AUDIT_MODULES.AUTH]: AUDIT_CATEGORIES.AUTH,
  [AUDIT_MODULES.INVENTORY]: AUDIT_CATEGORIES.INVENTORY,
  [AUDIT_MODULES.INVOICE]: AUDIT_CATEGORIES.SALES,
  [AUDIT_MODULES.PO]: AUDIT_CATEGORIES.PURCHASE,
  [AUDIT_MODULES.SECURITY]: AUDIT_CATEGORIES.SECURITY,
  [AUDIT_MODULES.SETTINGS]: AUDIT_CATEGORIES.SYSTEM,
  [AUDIT_MODULES.PRODUCT]: AUDIT_CATEGORIES.INVENTORY,
  [AUDIT_MODULES.USER]: AUDIT_CATEGORIES.SYSTEM,
  [AUDIT_MODULES.RBAC]: AUDIT_CATEGORIES.SECURITY,
  [AUDIT_MODULES.REPORT]: AUDIT_CATEGORIES.REPORT,
};

export function resolveAuditCategory(module: string): string {
  return MODULE_CATEGORY_MAP[module] ?? AUDIT_CATEGORIES.SYSTEM;
}

export const SECURITY_AUDIT_ACTIONS = new Set<string>([
  AUDIT_ACTIONS.LOGIN,
  AUDIT_ACTIONS.LOGOUT,
  AUDIT_ACTIONS.LOGIN_FAILED,
  AUDIT_ACTIONS.PERMISSION_DENIED,
  AUDIT_ACTIONS.UNAUTHORIZED_ACCESS,
  AUDIT_ACTIONS.PASSWORD_CHANGED,
  AUDIT_ACTIONS.PASSWORD_RESET_REQUESTED,
  AUDIT_ACTIONS.PASSWORD_RESET_COMPLETED,
]);
