export const DEFAULT_SETTINGS = [
  {
    key: 'sales.max_discount_staff',
    value: '10',
    type: 'NUMBER',
    group: 'SALES',
    description: 'Max discount percentage for staff',
  },
  {
    key: 'sales.max_discount_manager',
    value: '30',
    type: 'NUMBER',
    group: 'SALES',
    description: 'Max discount percentage for manager',
  },
  {
    key: 'inventory.allow_negative_stock',
    value: 'false',
    type: 'BOOLEAN',
    group: 'INVENTORY',
    description: 'Allow stock below zero',
  },
  {
    key: 'inventory.low_stock_threshold',
    value: '20',
    type: 'NUMBER',
    group: 'INVENTORY',
    description: 'Default low stock threshold',
  },
  {
    key: 'receipt.show_store_name',
    value: 'true',
    type: 'BOOLEAN',
    group: 'RECEIPT',
    description: 'Show store name on printed receipt',
  },
  {
    key: 'receipt.show_store_phone',
    value: 'false',
    type: 'BOOLEAN',
    group: 'RECEIPT',
    description: 'Show store phone on printed receipt',
  },
  {
    key: 'receipt.show_store_address',
    value: 'false',
    type: 'BOOLEAN',
    group: 'RECEIPT',
    description: 'Show store address on printed receipt',
  },
  {
    key: 'tax.business_name',
    value: '',
    type: 'STRING',
    group: 'TAX',
    description: 'Business name for S1a-HKD tax report',
  },
  {
    key: 'tax.tax_code',
    value: '',
    type: 'STRING',
    group: 'TAX',
    description: 'Tax code (MST) for S1a-HKD tax report',
  },
  {
    key: 'tax.business_location',
    value: '',
    type: 'STRING',
    group: 'TAX',
    description: 'Business location for S1a-HKD tax report',
  },
  {
    key: 'tax.revenue_group_1_label',
    value: 'Bán hàng doanh nghiệp',
    type: 'STRING',
    group: 'TAX',
    description: 'Label for revenue group 1 on tax report',
  },
  {
    key: 'tax.revenue_group_1_types',
    value: 'COMPANY,GROUP',
    type: 'STRING',
    group: 'TAX',
    description: 'Comma-separated CustomerType values for revenue group 1',
  },
  {
    key: 'tax.revenue_group_2_label',
    value: 'Bán hàng khách vãng lai',
    type: 'STRING',
    group: 'TAX',
    description: 'Label for revenue group 2 on tax report',
  },
  {
    key: 'tax.revenue_group_2_types',
    value: 'INDIVIDUAL,NONE',
    type: 'STRING',
    group: 'TAX',
    description: 'Comma-separated CustomerType values for revenue group 2 (NONE = no linked customer)',
  },
] as const;
