export const DEFAULT_SETTINGS = [
  {
    key: 'sales.max_discount_staff',
    value: '10',
    type: 'NUMBER',
    group: 'SALES',
    description: 'Max discount percentage for staff',
  },
  {
    key: 'sales.max_discount_manager',
    value: '30',
    type: 'NUMBER',
    group: 'SALES',
    description: 'Max discount percentage for manager',
  },
  {
    key: 'inventory.allow_negative_stock',
    value: 'false',
    type: 'BOOLEAN',
    group: 'INVENTORY',
    description: 'Allow stock below zero',
  },
  {
    key: 'inventory.low_stock_threshold',
    value: '20',
    type: 'NUMBER',
    group: 'INVENTORY',
    description: 'Default low stock threshold',
  },
  {
    key: 'receipt.show_store_name',
    value: 'true',
    type: 'BOOLEAN',
    group: 'RECEIPT',
    description: 'Show store name on printed receipt',
  },
  {
    key: 'receipt.show_store_phone',
    value: 'false',
    type: 'BOOLEAN',
    group: 'RECEIPT',
    description: 'Show store phone on printed receipt',
  },
  {
    key: 'receipt.show_store_address',
    value: 'false',
    type: 'BOOLEAN',
    group: 'RECEIPT',
    description: 'Show store address on printed receipt',
  },
] as const;
